version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: portfolio_server
    restart: unless-stopped
    networks:
      - portfolio_net
    ports:
      - '3001:3001'
    volumes:
      - db_data:/app/server/database
    environment:
      - PORT=3001
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/api/portfolio/it || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: portfolio_client
    restart: unless-stopped
    networks:
      - portfolio_net
    expose:
      - '80'

volumes:
  db_data:

networks:
  portfolio_net:
    driver: bridge
