version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: portfolio_server
    restart: unless-stopped
    networks:
      - portfolio_net
    environment:
      - PORT=3001
    volumes:
      - db_data:/app/server/database
    expose:
      - '3001'
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/api/portfolio/it || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: portfolio_client
    restart: unless-stopped
    networks:
      - portfolio_net
    expose:
      - '80'

  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - client
      - server

networks:
  portfolio_net:
    driver: bridge

volumes:
  db_data:
  caddy_data:
  caddy_config:
