version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: portfolio_server
    ports:
      - '3001:3001'
    volumes:
      - db_data:/app/server/database
    environment:
      - PORT=3001

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: portfolio_client
    ports:
      - '5173:80'

volumes:
  db_data:
